
name: Protobuf Python client generator

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: install dependencies
      run: |
        mkdir -p generated/lemon_pi
        pip install "grpcio>=1.53.0" "grpcio-tools>=1.53.0" "protobuf>=3.24.1"

    - name: generate client code
      id: generate
      run: |
        python -m grpc_tools.protoc \
               --python_out=generated/lemon_pi \
               -I=src/main/proto \
               lemon-pi.proto race-flag-status.proto
        if [[ $(git diff --stat) != '' ]]; then
          echo "diff_state=dirty" >> $GITHUB_ENV
          echo "changes made"
        else
          echo "diff_state=clean" >> $GITHUB_ENV
        fi

    - name: pull-request
      if: env.diff_state == 'dirty'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch-suffix: 'timestamp'
        base: master
        delete-branch: true
        title: 'Generate Python Client.md'
        body: |
          Update generated python code
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        assignees: sprintf